services:
  - type: web
    name: minyo-platform
    runtime: python
    buildCommand: ./build.sh
    startCommand: gunicorn minyo_platform.wsgi:application
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.11
      - key: DJANGO_ALLOWED_HOSTS
        value: .onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: minyo-db
          property: connectionString

databases:
  - name: minyo-db
    plan: free 