services:
  - type: web
    name: minyo-platform
    env: python
    buildCommand: "chmod +x build_files.sh && ./build_files.sh"
    startCommand: "gunicorn minyo_platform.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: minyo-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.13.3
      - key: WEB_CONCURRENCY
        value: 4

databases:
  - name: minyo-db
    databaseName: minyo
    user: minyo_user
    plan: free 